### ISSUE TITLE
[1.17] Fortune Hammer

### ISSUE THREAD

**Issue by kaiserkalt** [kwpugh/gobber_fabric-1.17#1]
Are hammers intended to not fortune ores? I have a fortune 3 hammer and it doesn't have any effect on any ore. 
Also, you might want to check the excavator with fortune, for gravel>flint. And both tools with silk touch, I haven't checked this enchant.

**Comment by kwpugh** [comment]
This is something that has eluded me in the past.  I have it on my list.

**Comment by kwpugh** [comment]
Ok, I checked on this this morning.   I checked my code and it covers enchantments on hammers.  I also ran repeated tests between a fortune 3 diamond pickaxe and fortune 3 hammers.  Both yield roughly the same number of drops.  I repeatedly broke 4 diamond ores with each and general got around 9 diamonds.  So I don't see a problem.

**Comment by kwpugh** [comment]
Also, tested the excavators against diamond shovels with fortune 3, and got flint with every break, comparable with the diamond shovels.

**Comment by kwpugh** [comment]
added to latest release.
