### ISSUE TITLE
[1.17.1] Recipes not working.

### ISSUE THREAD

**Issue by drakosoldier298** [kwpugh/gobber_fabric-1.17#11]
https://gist.github.com/drakosoldier298/34525bd5c2190aef359e4c8f70029e92 client side log.
So using gobber 1.17.1-2.4.38 Recipes are not working at all

**Comment by kwpugh** [comment]
try updating to the latest of Additional Additions, v2.1.1

**Comment by drakosoldier298** [comment]
It did not work,

**Comment by kwpugh** [comment]
looks like you are using an outdated version of architectury, which REI needs.  There is also a newer version of REI.

**Comment by drakosoldier298** [comment]
Updated both architectuary and rei, and Still cant check recipes for gobber.

**Comment by drakosoldier298** [comment]
https://paste.ee/p/uXdTO heres the new log

**Comment by kwpugh** [comment]
Are you seeing recipes from any other mods?

**Comment by drakosoldier298** [comment]
Yes the only other mod that doesnt have any recipes is, Wireless networks, By the cafeteria devs.

**Comment by kwpugh** [comment]
are you using any data packs?  Have you tried disabling to see?

**Comment by drakosoldier298** [comment]
No datapacks One of my admins set up kubkjs to replace all recipes that use sticks to also use stone rods though

**Comment by kwpugh** [comment]
well my recipes don't use sticks, they use Gobber rods.   at this point it sounds like you have a mod and/or data pack conflict.  you will need to start disabling them one at a time and see which one is involved.

**Comment by Merith-TK** [comment]
this is our kubejs script
it only touches

`adorn:stone_rod`
`blockus:legacy_stonecutter`
`minecraft:chest`
`minecraft:crafting_table`
`minecraft:cobblestone`
`minecraft:stick`
`minecraft:stone`
`minecraft:stonecutter`
```js
// priority: 0

settings.logAddedRecipes = true
settings.logRemovedRecipes = true
settings.logSkippedRecipes = false
settings.logErroringRecipes = true

console.info('Hello, World! (You will see this line every time server resources reload)')

onEvent('recipes', event => {
	// Make Stone Rods Usable as a actual "stick" item in recipies as they serve no use outside of stone torches
	event.replaceInput({}, 'minecraft:stick', '#fabric:stick')

	// replace 'blockus:legacy_stonecutter' with 'minecraft:crafting_table'
	event.remove({id: 'blockus:legacy_stonecutter'})
	event.shapeless('1x blockus:legacy_stonecutter', ['minecraft:stonecutter'])
	event.shaped('1x minecraft:crafting_table', [
		'XX', 'XX'
	], {
		X: "minecraft:cobblestone"
	})


	// Make Stone Rods craftable with cobble
	event.shaped('4x adorn:stone_rod', [
		'S  ',
		'S  ',
		'   '
	], {
		S: 'minecraft:cobblestone'
	})

	// Make Chests Craftable with stone
	event.shaped('minecraft:chest', [
		'SSS',
		'S S',
		'SSS'
	], {
		S: 'minecraft:stone'
	})

	// ##
})

onEvent('items.tags', event => {
	// Define the "fabric:stick" tag and add sticks and stone_rods to it
	event.add("fabric:stick", "minecraft:stick")
	event.add("fabric:stick", "adorn:stone_rod")
})
```

**Comment by kwpugh** [comment]
did you try without the script running?

**Comment by drakosoldier298** [comment]
after getting around to single player testing it seems to be a serverside issue, testing without kubejs now

**Comment by Merith-TK** [comment]
We think we found the issue, not existing on the server

**Comment by kwpugh** [comment]
that would do it

**Comment by drakosoldier298** [comment]
I am so sorry. Im a dumbass...the server doesnt have gobber on it...

**Comment by kwpugh** [comment]
Glad you figured it out.  Enjoy the mod!
