### ISSUE TITLE
[1.1.7.1] Conflict with other mods that that don't use required=false in tool jsons

### ISSUE THREAD

**Issue by FrostByteYT** [kwpugh/gobber_fabric-1.17#12]
I use an Iron pick on the lucky block and the diamond pick on the normal gobber ore but after I mine it nothing drops at all even if I spawn in a gobber pickaxe it doesn't drop gobber

**Comment by kwpugh** [comment]
This is caused by the conflicts between two tool approaches available in Fabric at the moment.

This should be fixable when the PR for new tool API is released:  https://github.com/FabricMC/fabric/pull/1629

**Comment by Muffintiem** [comment]
Weird thing is despite having the same mods and everything, while vanilla tools can't mine at all, Gobber tools work fine if I'm using the vanilla launcher but drop nothing if I'm using MultiMC as my launcher. Which honestly doesn't make much sense since the launcher shouldn't affect game play. The only thing can think of is that perhaps MultiMC loads mods in a different order than vanilla and that change breaks it.

**Comment by kwpugh** [comment]
Mod loading around is mostly random and controlled by the fabric loader

**Comment by kwpugh** [comment]
do you have any ore/tool mods that you disabled sets from?

**Comment by Muffintiem** [comment]
That did it. I had disabled the armor and tool sets from Better End/Better Nether because I didn't want them to show up in REI. (I had wanted the ores in those to only be building materials like the way Vanilla Copper is) I wonder if there's a way I could turn them off without causing this problem.

**Comment by kwpugh** [comment]
which items  did you disable?

**Comment by kwpugh** [comment]
Looks like the author knew about the problem but was not aware of the easy fix:  https://github.com/paulevsGitch/BetterNether/issues/413

**Comment by kwpugh** [comment]
This is up  to  the author of BetterNether/BetterEnd  to fix on their end or you will need to disable the recipes via data pack.

**Comment by Muffintiem** [comment]
I'll probably just disable the recipes via either a datapack or KubeJS since the ones for Better End still show up even if I set them to "false", what's a few more?

**Comment by kwpugh** [comment]
up to other mod authors to add the required=false tags to their  jsons
