### ISSUE TITLE
[1.17.1] Last update crash

### ISSUE THREAD

**Issue by kryptongamer** [kwpugh/gobber_fabric-1.17#13]
Last update crash server in END dim.

https://pastebin.com/upEg910q

**Comment by Muffintiem** [comment]
I'm having this same bug in the End as well as a variant in the overworld that happens with random mobs. All have the **`net.minecraft.class_1297.handler$bjp000$gobberCanFreeze(class_1297.java:10989)`** line in them just like the End crashes.

**Comment by Muffintiem** [comment]
So I noticed that there were a few popular performance enhancing mods in both op's and my game so I decided to see if it was a conflict. I took out Ferritecore and lo and behold the crash stopped happening so I think Gobber might not be playing nicely with Ferritecore. Unfortunately without it my performance is awful with the game stuttering frequently.

**Comment by kwpugh** [comment]
This will be fixed in next update.
