### ISSUE TITLE
[1.17.1] enableDragonFlight is broken

### ISSUE THREAD

**Issue by red2blue** [kwpugh/gobber_fabric-1.17#15]
latest mc
latest gobber2
fabric

-

Setting this to false does not do anything. Dragon armor still allows creative flight..

**Comment by kwpugh** [comment]
option has been removed.  I may look at creating a separate set of flying and non-flying dragon armor in the future.

**Comment by red2blue** [comment]
Yep yep. Talked to you about it in discord last night. Thanks for
entertaining the idea
