### ISSUE TITLE
Flashing Nether Ore and missing drops using Paxels.

### ISSUE THREAD

**Issue by Muffintiem** [kwpugh/gobber_fabric-1.17#18]
I have noticed that for some odd reason the Nether Ore is flashing. I'm not sure when it started doing it because I hadn't been to the Nether in a while but it wasn't doing it the last time I was in the Nether so I'm not sure it's intended behavior.

Also while the Paxels are now stripping the Cinnamon Logs from Croptopia properly, they still aren't dropping the Cinnamon.

**Comment by kwpugh** [comment]
Thanks. for the report.
- the flashing is caused by better nether and better end, they re-wrote how. texture meta is handled.   Still trying to figure that out.
- Already have an issue open one the cinnamon drops.

**Comment by Muffintiem** [comment]
Interesting about the flashing being caused by Better End and Nether. Is that also the cause of the Overworld Gobber and End Gobber glowing? I thought it was neat that they glowed because they are powerful substances but I wondered why the Lucky Gobber wasn't glowing.

**Comment by kwpugh** [comment]
Lucky blocks do not have that animation.
