### ISSUE TITLE
[1.17.1] Gobber Full Armor Water Breathing - Not Working

### ISSUE THREAD

**Issue by JollyGreenFox** [kwpugh/gobber_fabric-1.17#19]
When equipping a full set of Gobber Armor, it does Provide the Healing and Feeding but doesn't provide the water breathing

**Comment by kwpugh** [comment]
What  other mods are you  running?

**Comment by kwpugh** [comment]
Note, the Atlantis mod breaks water breathing if you are running that one.

**Comment by kwpugh** [comment]
![Screen Shot 2021-09-05 at 10 32 13 AM](https://user-images.githubusercontent.com/8809210/132132430-8c29f7a5-94c9-4c56-af78-fa293e6f70bc.png)

Seems to work just fine, you need to provide more info about what you are using.

**Comment by kwpugh** [comment]
Please provide a listing of other mods you are running, otherwise I can do nothing.

**Comment by kwpugh** [comment]
Existing issue with Atlantis:  https://github.com/Exploding-Creeper/atlantis/issues/32
