### ISSUE TITLE
[1.17.1] Ring does not work in this world

### ISSUE THREAD

**Issue by christianfirecup** [kwpugh/gobber_fabric-1.17#21]
when i use a ring it says it cannot work in this world is there anyway to fix this

**Comment by kwpugh** [comment]
could you be a bit more specific?  which ring?

**Comment by kwpugh** [comment]
it is likely a ring that is designed to work in certain vanilla worlds.

**Comment by christianfirecup** [comment]
> it is likely a ring that is designed to work in certain vanilla worlds.

is there any way to make them universal

**Comment by kwpugh** [comment]
what ring are you talking about?

**Comment by christianfirecup** [comment]
> what ring are you talking about?

I'm using a mod called mutiworld that generates a second overworld  it affects the tp rings

**Comment by kwpugh** [comment]
I think I have it working in modded dimensions.  Can you give this version a try and confirm please?

[Gobber2-Fabric-1.17.1-2.4.45.jar.zip](https://github.com/kwpugh/gobber_fabric-1.17/files/7138295/Gobber2-Fabric-1.17.1-2.4.45.jar.zip)

**Comment by kwpugh** [comment]
Actually, try this one  instead.  I added a second ring and a recipe, so players can upgrade existing rings  to new rings.

[Gobber2-Fabric-1.17.1-2.4.45.jar.zip](https://github.com/kwpugh/gobber_fabric-1.17/files/7139949/Gobber2-Fabric-1.17.1-2.4.45.jar.zip)

**Comment by kwpugh** [comment]
Ok, after a bunch of testing, this is now in v2.4.45, enjoy. Let me know if you run into any issues.
