### ISSUE TITLE
[1.18] Lucky Gobber not generating in 1.18 Experimental

### ISSUE THREAD

**Issue by Muffintiem** [kwpugh/gobber_fabric-1.17#22]
I'm using the version of Gobber for 1.18 Experimental Snapshot 6 and while regular Gobber is generating fine I can't find Lucky Gobber anywhere.

**Comment by kwpugh** [comment]
Yikes, I see I some how deleted the registry entry.  Will add back and publish a new version.  Sorry.

**Comment by kwpugh** [comment]
fixed in Gobber2-Fabric-1.18-2.5.1

**Comment by Muffintiem** [comment]
Speaking of the Lucky Block, how would I go about making a datapack to change the drops? I've only made datapacks for vanilla chests.

**Comment by kwpugh** [comment]
Here is a sample for server I played on.  Adjust to your needs.

[dank_server.zip](https://github.com/kwpugh/gobber_fabric-1.17/files/7139719/dank_server.zip)
