### ISSUE TITLE
[1.18 snapshots]

### ISSUE THREAD

**Issue by SphericAcid** [kwpugh/gobber_fabric-1.17#23]
![image](https://user-images.githubusercontent.com/90434148/133830498-e8b87b7f-690f-49ad-b56d-30697cbdded9.png)

**Comment by kwpugh** [comment]
what is the problem, this is of now value.

**Comment by kwpugh** [comment]
If you are trying to run Gobber on snapshot, use the 1.18 version of Gobber.

https://www.curseforge.com/minecraft/mc-mods/gobber-fabric/files/3459962
