### ISSUE TITLE
[1.18] Gilded Nether Gobber?

### ISSUE THREAD

**Issue by Muffintiem** [kwpugh/gobber_fabric-1.17#24]
Since you added Gilded Carbonado to More Gems I was wondering if a Gilded version of Nether Gobber was possible.

**Comment by kwpugh** [comment]
I added Gilded to MoreGems 1.18, I may do the same to 1.18 Gobber as well.

**Comment by Muffintiem** [comment]
Oh the gilded Carbonado is a 1.18 only feature? I was waiting for the 1.17.1 version of More Gems to update with it since I'm currently running 2 separate instances. A 1.18 one where I'm just playing by myself with only a handful of mods and a 1.17.1 one where I'm building a huge modpack for a private LAN world.

**Comment by kwpugh** [comment]
in 1.18+ Nether Chestplate has builtin Piglin protection.
