### ISSUE TITLE
[1.17.1] Ore drop issue

### ISSUE THREAD

**Issue by Muffintiem** [kwpugh/gobber_fabric-1.17#25]
Neither Gobber nor More Gems ores are dropping anything since most recent update for 1.17.1. Tried different tools and none of them worked.

Also I'm wondering if you could put in an alternate ore generation similar to 1.18 that works with world gen mods that change the world height like Terralith. I'm finding Carbonado way too high.

**Comment by kwpugh** [comment]
Just test with iron, diamond  and Netherite pickaxes and breaking/dropping works fine.  Perhaps you have  a mod that is breaking things.  What else are you playing with?

**Comment by kwpugh** [comment]
In particular, there are  mods that decided to use the new mineable tags instead of the Fabric Tools API, which are not compatible with each other.  There is a Fabric PR coming that should  fix it.

**Comment by kwpugh** [comment]
Which mods do you have  that add mining tools?

**Comment by kwpugh** [comment]
Regarding the world height ore spawning, that is now in 1.18, which officially added the new world features.

**Comment by kwpugh** [comment]
Since this is the same issue as reported by others, I am closing this with a link to the existing one.  https://github.com/kwpugh/gobber_fabric-1.17/issues/12

**Comment by Muffintiem** [comment]
I think this one is slightly different. I realized mine started when I switched to using MultiMC as my launcher. I ran the game in the vanilla launcher, with the same exact mods, and while the vanilla tools were still broken, Gobber tools were able to mine both Gobber and More Gems ores.

**Comment by Muffintiem** [comment]
As for the ore heights, if the lowest and highest heights could be set in the config and it accepted negative y heights then that would be a good compromise for people using mods in 1.17.1 that extend the world height. This would be useful in both Gobber and More Gems.
