### ISSUE TITLE
Config enhancement

### ISSUE THREAD

**Issue by Muffintiem** [kwpugh/gobber_fabric-1.17#26]
I noticed that a max height for ores exists in the config but not a minimum. I'd like to be able to set it in the config so certain ores don't appear below a certain threshold to motivate mining at different heights. Also ores should have the ability to replace deepslate too.

**Comment by kwpugh** [comment]
Those are features in 1.18, not 1.17.1.

1.17.1 is feature complete.  It will only get significant bug fixes at this point.
