### ISSUE TITLE
[1.17.1] Fortune not working on Amethyst Shards on Gobber Tools

### ISSUE THREAD

**Issue by rc8marcelo** [kwpugh/gobber_fabric-1.17#27]
I've tried mining amethyst shards using both a gobber hammer and pickaxe that had fortune 3 and so far I didn't get more than a max of 4 I think. I tried with a diamond pick with fortune 3 and I confirm that I get the crazy amount of shards you get when you mine them.

The gobber pick and hammer work properly on other ores, this I can confirm cuz I mined a few diamonds awhile ago and saw that they worked properly. I'm running Gobber 2.4.48 on MC 1.17.1

**Comment by kwpugh** [comment]
Figured it out, turns out Minecraft has a special tag for clusters to get extra drops, cluster_max_harvestables.json, that needs my tools added to.

Will be in next update.

**Comment by kwpugh** [comment]
Fixed in v51
