### ISSUE TITLE
[1.17.1] No xp sounds when you have Medallion of Experience on Off Hand

### ISSUE THREAD

**Issue by rc8marcelo** [kwpugh/gobber_fabric-1.17#28]
A slightly minor bug I found. I just crafted a Medallion of Experience and found that the XP you get from killing mobs doesn't give a sound when you "absorb" them. 

I'm running Gobber 2.4.48 on MC 1.17.1

**Comment by kwpugh** [comment]
Odd, I get the sound.  The latest version is .50, might try that before we go much further on debugging.
