### ISSUE TITLE
[1.18] New Bow Enchants?

### ISSUE THREAD

**Issue by Muffintiem** [kwpugh/gobber_fabric-1.17#29]
I feel the bows are getting left out when it comes to enchantments. Personally I'd really like there to be a bow version of Looting and maybe Wisdom and/or "Shulker Blade" (maybe it could be called something like "Shulker Point"?).

**Comment by kwpugh** [comment]
If I add anything, it will be for 1.18 at this point.  1.17.1 is basically getting bug fixes.

**Comment by Muffintiem** [comment]
Luckily I use both depending on what I'm doing. And while parity between the two would be nice it's understandable if you don't want to maintain both.

**Comment by kwpugh** [comment]
Gobbers bows are already pretty powerful.  I am adding a couple of bow enchants to MoreGems for 1.18.
