### ISSUE TITLE
No recipes for Medallion of healing.

### ISSUE THREAD

**Issue by SirElCid** [kwpugh/gobber_fabric-1.17#3]
Hello,

I have the Gobber mod and the REI (Roughly Enough Items) mod. I am able to see all the recipes so I can recreate the items, unfortunately the medallion of healing, lesser healing and greater healing don't show up at all. Is this supposed to happen?

I've tried finding the recipes for them to no avail. I love the mod so is it too much to just ask what the recipes are?

**Comment by kwpugh** [comment]
Oh sorry, some how those get lost some point.   I push an update shortly.

**Comment by kwpugh** [comment]
Fixed in v28
