### ISSUE TITLE
1.17.1 Trinket Compatibility

### ISSUE THREAD

**Issue by SWEET-P0TATO** [kwpugh/gobber_fabric-1.17#30]
Like all accessory mods, there is a discrepancy when equipping rings or charms in the trinket mod based on the variety of slot it offers. If possible, find a solution to make this possible, it would be the best for those who like to equip themselves and enjoy the benefits that it entails.

**Comment by kwpugh** [comment]
No plans in the near future to add Trinkets.  No  issue ticket needed for this at this point.
