### ISSUE TITLE
[1.18] Fire Aspect not dropping cooked meat

### ISSUE THREAD

**Issue by Muffintiem** [kwpugh/gobber_fabric-1.17#31]
When I use Fire Aspect on any of the Gobber Swords including Sword of the Sniper, mobs still drop raw meat and Zombies occasionally drop uncooked potatoes. Flame Enchant on Bows seems to work fine. Also despite having Fire Aspect mobs don't catch on fire with Sword of the Sniper arrows.

**Comment by kwpugh** [comment]
Are you aware of any other modded swords that work properly with Fire Aspect?

As I understand, fire aspect is controlled by vanilla entity loot tables (JSONS).

**Comment by kwpugh** [comment]
ok, I admittedly am not familiar with or a big user of Fire Aspect, so I went into 1.17.1 and tried with the Gobber swords, they set sheep and cows o n fire and dropped cooked meat.  I guessing that fire aspect is gained by modded sword extending the vanilla SwordItem.  If it is not working for you, I'm wondering if another mod somehow messed up the drop tables.

**Comment by Muffintiem** [comment]
Hmmm. I only have Gobber and More Gems and Greater Eye and a few display related mods. It turns out that somewhere along the way that Fire Aspect was dropped (I have a mod that uses the grindstone to take enchantments from items and put them into books). I added it back on and while it works if I use the Sword of the Sniper as a sword, the ones hit by arrows aren't dropping cooked meat. Which is odd as Shulker Blade and Looting are carrying over to the arrows fine.

**Comment by kwpugh** [comment]
the arrow part of the sword of the sniper has no logic for in it for enchantments

**Comment by kwpugh** [comment]
I can add a bit of code to make Fire Aspect work on the arrow for Sword of the Sniper

**Comment by kwpugh** [comment]
added fire aspect to arrows in v55
