### ISSUE TITLE
1.17.1 diorite portal

### ISSUE THREAD

**Issue by ITSLOCKED** [kwpugh/gobber_fabric-1.17#32]
anytime I enter the caving world portal it spawns me above bedrock I don't know if anyone else has this issue but it keeps happening anytime I go through the portal in any world

**Comment by kwpugh** [comment]
Yeah, that can happen.  Did you try making a portal at a different location?

**Comment by kwpugh** [comment]
This was addressed with a previous update to the customportalsapi.
