### ISSUE TITLE
[1.17.1] Crashing on start

### ISSUE THREAD

**Issue by Bulbarat** [kwpugh/gobber_fabric-1.17#36]
Whenever I try to run the game, it crashes and says "Could not find required mod: gobber2 requires {fabricloader @ [>=0.12.5]}"
I have fabric-api-0.42.1+1.17, do i specifically need 0.42.0?

**Comment by kwpugh** [comment]
depending on which launcher you are using, you also need to update its fabric  loader to version 0.12.5

Fabric API is a separate  thing.
