### ISSUE TITLE
[1.18.1] Using any gobber hammer crashes the game

### ISSUE THREAD

**Issue by SailoX** [kwpugh/gobber_fabric-1.17#39]
Attempted on various blocks (modded such as modern industrialization ores, and oddly enough, unmodded such as a dirt block, though you can still mine deepslate and similar stone with it, modded or not.) Crash is only client side it seems. Log down below.
[crash-2021-12-26_06.59.05-client.txt](https://github.com/kwpugh/gobber_fabric-1.17/files/7777060/crash-2021-12-26_06.59.05-client.txt)

**Comment by SailoX** [comment]
Should be noted, that all hammers do this.

**Comment by kwpugh** [comment]
Just test on another modpack and it works fine.  I'm guessing you have another mod in there that is doing something that conflicts with my mod.  Sodium is the first usual suspect of weird errors, so you might try disabling that and test.  If it is not Sodium, you with have to start disabling mods until you find which one it is, then I can take a look at what they are doing and what might be going wrong.

**Comment by kwpugh** [comment]
and by "all hammers" do you mean all the Gobber hammers or all hammers from other mods?

**Comment by SailoX** [comment]
Testing to see. I also have vanilla hammers in this mod pack.

**Comment by SailoX** [comment]
Nope, vanilla hammers does not crash. Only gobber ones.

**Comment by kwpugh** [comment]
that error seems to be a client side mixin error and oddly the hammers do not utilize any mixins

**Comment by SailoX** [comment]
I am not sure what that means. I do not understand crash logs most of the time, and was told by the modpack owner to submit the report to yhe maker of this awesome mod.

**Comment by SailoX** [comment]
The strange thing is, the other tools from gobber work perfectly.

**Comment by kwpugh** [comment]
are you using a published modpack or your own creation?

**Comment by SailoX** [comment]
Published modpack. Benchmark II version 0.4.4

**Comment by kwpugh** [comment]
you might want to report to their issue log, they might be already looking into it.

**Comment by SailoX** [comment]
The owner told me to report this crash to you lol

**Comment by kwpugh** [comment]
lol.  since there are hundreds of mods in that pack and I can not replicate, it is not something I'm going to try to hunt down.  sorry.

**Comment by SailoX** [comment]
That's fair enough!

**Comment by SailoX** [comment]
The owner of the mod pack is going to see what the issue is, I can let you know when I find out!

**Comment by kwpugh** [comment]
This is fixed as in Gobber2-Fabric-1.18.1-2.5.63.1

Also fixed in 1.18.2
