### ISSUE TITLE
[1.17.1] Excavator not working

### ISSUE THREAD

**Issue by rc8marcelo** [kwpugh/gobber_fabric-1.17#4]
I have a Gobber excavator and it isn't digging out an area for some reason. I dunno if I'm using it wrong but that's how I use the hammers and it works how I expected it to.

Evidence:
https://user-images.githubusercontent.com/341493/125799504-5b0eef49-d26d-491e-b0ac-497ef70df099.mp4

**Comment by kwpugh** [comment]
What version of Gobber are you using?

**Comment by rc8marcelo** [comment]
I'm using 2.4.28. Also I don't know if this is a bug or intended but I have a silk touch hammer and the blocks surrounding the block that I mine out are not silk touched (ex stone gives me 1 stone and 8 cobblestone) is this intentional? I noticed this as I was mining out stone and instead of getting gobber ore blocks I got the globette

**Comment by kwpugh** [comment]
Couple things:
- using 2.4.28 excavators test fine on my side, both with or without enchantments.  **are you playing on a server or single player?**   I'm thinking there is some sort of mod conflict going on.
- Silk Touch on the hammer is an overbite, I will take a look at that
- The Gobber ores have been changed to better match the vanilla mech of dropping raw ore, so they drop globettes instead, which are crafted into globs and used to make ingots

**Comment by rc8marcelo** [comment]
I'm playing single player...yeah it might be a mod conflict I guess. Its hard to say but the only mod I have that changes mining behavior, as far as I know, is Gobber but thats ok. If it works on your end then it must be something else on my mods.

On your last bullet point yes I think that was an expected behavior without silk touch. I think you get more out of mining the ore using silk touch since its more efficient to smelt them over using fortune (since you need 9 globettes) and thats how I discovered the silk touch hammer thing cuz I wanted to branch mine the gobber ores haha

**Comment by rc8marcelo** [comment]
**Update**: Its working. I don't know if my specific survival excavator is the only thing thats broken or if its because it came from an older version. 

I tried getting excavators through creative to test out all 3 and they work. Guess I'll just have to make a new one 😂

I'll close the issue now since it looks like a very unfortunate case with my specific excavator.

**Comment by kwpugh** [comment]
By the way, are you using either of my Emerald Tools or More Gems mods in your setup?   If so, which versions are you using?

**Comment by rc8marcelo** [comment]
None of those, these are all my mods in the fabric mods folder:

![image](https://user-images.githubusercontent.com/341493/125816038-ad74e346-c27c-4547-b701-a8e1f8739cdd.png)

Something to note:

* It appears that I can't make an excavator in my current world that works properly, yet in the test world I created awhile ago (creative) I am able to craft and make excavators that work
* If I get an excavator via creative, the excavators behavior is correct (so I kinda just "cheated" and crafted a broken one, thrown in into lava and took 1 from creative lmao)

**Comment by kwpugh** [comment]
that is very odd.   none of those mods would seem to conflict with a tool.   And working in one world but not in another is doubly odd.

**Comment by rc8marcelo** [comment]
Yep thats why I resigned to thinking its something with the world I'm in. It doesn't make sense to me and I haven't ever read the code of Minecraft so idk what caused it. But what I can say at least is on other worlds it works so I dont think its a bug on the mod itself

**Comment by kwpugh** [comment]
well, it's always troubling to me when there isn't reasonable explanation for a bug.

BTW:  I figured out how to pick up the silk touch part on the hammers.  Should show up in next update.

**Comment by rc8marcelo** [comment]
Hi, I don't know if I should re-open this but I think I figured out what was wrong with my excavator and how I managed to replicate it not working. 

I don't normally keep the excavator on my inventory since I don't do a lot of digging. I noticed when I store my excavator inside an ender chest and leave it there and close the game it stops working the next time I open the game to play. I was able to make it work again by simply quitting to main menu  then loading the save again so I guess its a bug but it doesn't disable the tool permanently.

**Comment by kwpugh** [comment]
I will try that on in my dev environment and see what happens

**Comment by kwpugh** [comment]
So I tried out the enderchest thing and it doesn't affect the hammer in multiple tests.

**Comment by rc8marcelo** [comment]
That's a different issue I raised but have so far not been able to reliably replicate (hammer). It happened to me today too when I first played but on both instances, this bug (excavator) and the other bug was fixed by simply quitting and reloading the game. I'd like to mention though that when I raised the previous issue (hammer) it wasn't fixing when I quit restart, I think it only really "reset" like this after I downloaded the latest build version.

When I get more free time maybe I'll try it on another world, see if it has anything to do with my current save or if I can replicate it in another survival game.

**Comment by kwpugh** [comment]
No other reports from other users, cannot replicate in dev, so nothing to be done of the development side.

**Comment by Dekonker** [comment]
I literally just had this same bug, it seems like it's some issue with the player specifically not the excavator. I let someone else on the server use my excavator and it worked for him but not for me. After logging out and in though the excavators started working.

**Comment by kwpugh** [comment]
very odd indeed.
