### ISSUE TITLE
[1.18.1] Find a way to deactivate Ring of Air Walking when dropped

### ISSUE THREAD

**Issue by Dbustard4981** [kwpugh/gobber_fabric-1.17#40]
ring of air walking and dragon armor not deactivating even when  take them out of inventory completely

**Comment by kwpugh** [comment]
Did you drop the ring while it was in your main hand?

**Comment by kwpugh** [comment]
Dragon armor has nothing to do with it.   If you drop the ring rather than deselecting it, the effect will be "stuck"

**Comment by Dbustard4981** [comment]
i just took it out of my hotbar at first but when the effect didnt wear off yes i through it out of my main hand... and with the dragon armor i am talking about the extra hearts it gives you i took the armor off but the hearts are still regenerating

**Comment by Dbustard4981** [comment]
and what do you mean by deselecting a ring

**Comment by kwpugh** [comment]
deselecting means not in mainhand.   As for the dragon armor, it is not design to remove the yellow hearts when removed.

**Comment by Dbustard4981** [comment]
so as for the world that i tossed the ring out in am i just screwed for that save or is there a fix

**Comment by kwpugh** [comment]
pull a new ring out of create and that should clear it up.

**Comment by Dbustard4981** [comment]
it worked ty :)

**Comment by kwpugh** [comment]
I'll take a look to see if there is a way to prevent this from happening

**Comment by kwpugh** [comment]
the air walking is fixed in v61

the dragon armor is working as designed.  It gives extra hearts and heals them, taking the armor off just removes the healing, so the extra hearts will go away if lost over time.
