### ISSUE TITLE
[1.18.1] tooltip not deleted when disabling armor abilities

### ISSUE THREAD

**Issue by Chuunkyz** [kwpugh/gobber_fabric-1.17#41]
i deleted the water breathing and auto feeding part of the regular gobber armor and i still have the "full armor provides :" tooltip
![_gobber](https://user-images.githubusercontent.com/81187289/147828420-04c2b40d-f454-4d1e-85bc-2e29d088567d.png)

**Comment by kwpugh** [comment]
I'll take a look, should be easy fix in the logic.

**Comment by kwpugh** [comment]
Fixed in v57 published to CurseForge
