### ISSUE TITLE
[1.18.1] Compatibility with the Skulk Worm mod? 

### ISSUE THREAD

**Issue by McHaunty** [kwpugh/gobber_fabric-1.17#42]
Could there be added compatibility with the Skulk Worm mod, with the quiet feet enchantment?
Link to Skulk Worm mod: https://www.curseforge.com/minecraft/mc-mods/fabric-sculk-worm

**Comment by kwpugh** [comment]
Did it not work when you tried?

**Comment by McHaunty** [comment]
> Did it not work when you tried?

No, the sculk worm still detected me when i had the enchantment on a pair of boots

**Comment by kwpugh** [comment]
The Worm mod is closed source so I cannot see what the author is doing.   There is no standard for the function for now, since the Warden was delayed to 1.19.  I messaged the author to ask them to share the sources.  If the author declines, nothing I can do with it for now.
