### ISSUE TITLE
[1.18.1]  Config Option for Acceptable Items in Enchantments

### ISSUE THREAD

**Issue by coolsimulations** [kwpugh/gobber_fabric-1.17#45]
Greetings,

Fellow mod developer here. I’m in the process of adding support for the Gobber tool materials in my mod (both Fabric and Forge) and have an issue. I would like to have my tools be able to have the Faster Obsidian Breaking enchantment be applied to them but current it’s hard coded to just the gobber tools. As a simple solution, can the accepted items in the enchantment be linked to a new config array option? it would be much appreciated and help immensely with my development.

**Comment by kwpugh** [comment]
Are you referring to this:
`	/*
	 *  So basically this does nothing since the enchantment
	 *  table screen handler pulls enchantments by type
	 *   in EnchantmentTarget
	 */
	@Override
	public boolean isAcceptableItem(ItemStack stack)
	{
		Item pickaxe = stack.getItem();

		if(pickaxe == ItemInit.GOBBER2_PICKAXE ||
				pickaxe == ItemInit.GOBBER2_PICKAXE_NETHER ||
				pickaxe == ItemInit.GOBBER2_PICKAXE_END ||
				pickaxe == ItemInit.GOBBER2_PAXEL ||
				pickaxe == ItemInit.GOBBER2_PAXEL_NETHER ||
				pickaxe == ItemInit.GOBBER2_PAXEL_END ||
				pickaxe == ItemInit.GOBBER2_PAXEL_STARS ||
				pickaxe == ItemInit.GOBBER2_HAMMER ||
				pickaxe == ItemInit.GOBBER2_HAMMER_NETHER ||
				pickaxe == ItemInit.GOBBER2_HAMMER_END)
		{
			return this.type.isAcceptableItem(stack.getItem());
		}
		else
		{
			return false;
		}

	}`

If you read the comment, you would have seen that the code does nothing because the way the enchantment table work.  That is why I had to actually had to do overrides in each tool base class:
`	@Override
	public float getMiningSpeedMultiplier(ItemStack stack, BlockState state)
	{
		Material material = state.getMaterial();
		
	 	if(ObsidianBreaking.fastAtObsidian(state, stack))
		{
			return ObsidianBreaking.fastObsidianSpeed();
		}
	 	
		return material != Material.METAL && material != Material.REPAIR_STATION && material != Material.STONE ? super.getMiningSpeedMultiplier(stack, state) : this.miningSpeed;
	}`

Unless you know another way.

**Comment by kwpugh** [comment]
What kind of Gobber support are you adding?

**Comment by coolsimulations** [comment]
For my Gobber support, I'm simply adding a Gobber, Nether, and End type to my multi-tool mod, which is rather different to your paxels.

I originally thought the getMiningSpeedMultiplier was all I needed. I did add ObsidianBreaking code to the method in my tool class. While the enchantment does work because of that, you can only obtain it via applying the book to the tool in an anvil on creative mode. An anvil on survival and the /enchant command does not work as they depend on the isAcceptableItem method. That is why I suggest this change.

In vanilla's Efficiency enchantment, shears have to be hardcoded in the enchantment class and the else returns super.isAcceptableItem. That's why whatever uses the Digger EnchantmentTarget works as the Digger target checks for instances of MiningToolItem. Your Faster Obsidian enchantment, if it's not one of the accepted picks, returns false, which is acceptable as otherwise, it would allow vanilla pickaxes to be enchanted as well, but makes it impossible to be applied to any other item of the Digger type such as my tool.

Some kind of config array option I think would be an acceptable solution.

![2022-01-02_07 46 46](https://user-images.githubusercontent.com/33711385/147860870-4ffe235b-838a-4c2f-afa8-c53a0d7e4bba.png)
![2022-01-02_07 46 59](https://user-images.githubusercontent.com/33711385/147860876-6ce15afc-4100-458c-ae03-bef87cf859a2.png)
![2022-01-02_07 52 23](https://user-images.githubusercontent.com/33711385/147860899-05c11c53-8271-4a1a-a992-c56191ef72c1.png)

**Comment by coolsimulations** [comment]
Actually, a confit option probably isn’t the best solution. What if someone added `minecraft:dried_kelp` to the config value? Since it doesn’t have the getMiningSpeedMultiplier needed it wouldn’t work.

Perhaps instead of a config option, some kind of public static list in the Faster Obsidian Enchantment class that isAcceptableItem checks against? As isAcceptableItem is only checked at runtime, loading order shouldn’t impact when the list is added to.

**Comment by kwpugh** [comment]
I don't want to increase the complexity of the enchantments further by opening them up to other tools.
