### ISSUE TITLE
[1.18.1]  Ring of Return disabled in config but spawns in chests anyway

### ISSUE THREAD

**Issue by pewblaze** [kwpugh/gobber_fabric-1.17#46]
i tried to disable the Ring of Return, but it didn't work correctly. 

![2022-01-03_23 04 42](https://user-images.githubusercontent.com/96242065/147985805-0c344947-b362-46f8-879e-627db649958f.png)

`	   ***********************
	   Enable-Disable Rings
	   ***********************
	*/
	"enableRingReturn": false,
	/* 
	   `

Did i forget something?

**Comment by kwpugh** [comment]
looks like I missed a flag for the config in the chest loot logic.

**Comment by kwpugh** [comment]
I will fix in the next update.

**Comment by kwpugh** [comment]
Also, you can disable chest loot, which means no Ring of  Return or Ring of Teleport in chests.

<img width="342" alt="Screen Shot 2022-01-03 at 5 07 36 PM" src="https://user-images.githubusercontent.com/8809210/147990015-1adc2c32-4b8f-456a-98c1-42a08bd251e2.png">

**Comment by pewblaze** [comment]
Ah i see thank you! I will try that :)

**Comment by kwpugh** [comment]
Fixed in next update.
