### ISSUE TITLE
[1.18.1] DragonArmorNoFlight does not get perks

### ISSUE THREAD

**Issue by Slugstur1** [kwpugh/gobber_fabric-1.17#47]
https://github.com/kwpugh/gobber_fabric-1.17/blob/8b3aa0151cd85aca590f42cc3f0c9f88e9772973/src/main/java/com/kwpugh/gobber2/items/armor/DragonArmorNoFlight.java#L47

The isWearingDragonArmor check is not correct in branch 1.18.1 and 1.18.0. It should be isWearingNoFlightDragonArmor.
In the 1.17.1 branch this is not an issue since there the isWearingDragonArmor checks for both types.

**Comment by kwpugh** [comment]
Good catch, will be fixed in next update.
