### ISSUE TITLE
[1.18.1] Wither Effect always gets removed after killing a Wither Skeleton

### ISSUE THREAD

**Issue by Slugstur1** [kwpugh/gobber_fabric-1.17#48]
https://github.com/kwpugh/gobber_fabric-1.17/blob/c75de2cd6ac308a86485da5357d39fbbc299ea6d/src/main/java/com/kwpugh/gobber2/util/PlayerSpecialAbilities.java#L196

After killing a Wither Skeleton the Wither effect gets removed, always. Even without any Gobber weapons or armor. If I kill a Wither Skeleton with a wooden sword and no armor the effect gets removed when the skeleton dies. 

Is this intentional?

**Comment by kwpugh** [comment]
Fixed in next update.
