### ISSUE TITLE
[1.18.1] [Request] Ability to enable/disable tools

### ISSUE THREAD

**Issue by Slugstur1** [kwpugh/gobber_fabric-1.17#49]
Right now you can enable/disable rings, staff and medallions pretty easy, but you can't do that for the tools. Maybe not all tools need it, but specially the paxels and the hammers could use it.

Currently the hammers make mining tools from other tech mods (Tech Reborn, Industrial Revolution, Modern Industrialization) quite obsolete, while being easier to obtain (at least in my opinion).

**Comment by kwpugh** [comment]
Both 1.17.1 and 1.18.1 have that ability

<img width="385" alt="Screen Shot 2022-01-05 at 8 16 47 AM" src="https://user-images.githubusercontent.com/8809210/148233975-6cddf7b1-682c-4b93-89b2-e25405af6623.png">

**Comment by kwpugh** [comment]
currently available in recent releases
