### ISSUE TITLE
[1.18.1] Unbreakable config option doesnt work for End Hammer

### ISSUE THREAD

**Issue by Futi63** [kwpugh/gobber_fabric-1.17#50]
The unbreakable config set to "false" should mean the End Hammer doesn't get an unbreakable perk but it actually does get the unbreakable perk with it being disabled as shown in the images.

![image](https://user-images.githubusercontent.com/34105472/148960464-6c6a1a02-03c4-4dfa-8a0e-bbc66744e64e.png)
![image](https://user-images.githubusercontent.com/34105472/148960632-d922ea35-e73f-465f-bb37-945e5cdb7296.png)

**Comment by Futi63** [comment]
No, the tool was spawned in after the config was updated and the server was restarted, all other end tools have lost the unbreaking when crafting or spawning them in, but the End Hammer when spawned in has this unbreakable perk still.

**Comment by kwpugh** [comment]
spawned in?   the unbreakable function only works on crafted items.

**Comment by kwpugh** [comment]
when the unbreakable is turned off, that affects survival crafting.  It does not affect creative mode.

**Comment by Futi63** [comment]
That's strange, with a few other tools when they're spawned in, e.g. sniper sword... in creative, they have lost the unbreakable perk if I spawn it in, just the hammer and the paxel seem to be the only 2 that spawn in with the perk.

**Comment by kwpugh** [comment]
it is only the tools that have AOE (3x3, 5x5).  I add the unbreakable to them when when checking to make sure they have the radius tags for that function.  Why does it matter on a survival server?  Only affects creative.

**Comment by kwpugh** [comment]
I can add a check for the config flag when I check for radius tag on those items I suppose.

**Comment by Futi63** [comment]
It's just because we've found it to be a bit powerful if the item is unbreakable, especially since the swords had it too, so we were trying to swap out the unbreakable tools for not unbreakable tools in the players inventories, but to do this it would mean having to manually craft hammers and paxels since spawning them in is giving unbreakable still.

**Comment by kwpugh** [comment]
Well timing is good, I was about ready to push an update of Gobber for 1.18.1, so I will add the config check

**Comment by Futi63** [comment]
Thank you so much! <3

**Comment by kwpugh** [comment]
Adjusted in v59 which is on CurseForge now.
