### ISSUE TITLE
[1.18.1] Gobber ores do not generate in custom BetterEnd biomes

### ISSUE THREAD

**Issue by MJRamon** [kwpugh/gobber_fabric-1.17#51]
Did a vast testing with /fill command flying around, and didn't find any of the ore in BetterEnd biomes. They do spawn in vanilla biomes, like dragon island.

Mod named RandOre, at the same time, generates in all biomes. Maybe problem is in slight difference in methods: https://github.com/IntelligentCreations/Randore/blob/1.18/main/src/main/kotlin/dev/intelligentcreations/randore/RandoreMod.kt

**Comment by kwpugh** [comment]
Are  any other modded ores showing up in the Better End biomes?   If so, which ones?

**Comment by MJRamon** [comment]
No other custom End ores are used, only Gobber, RandOre and BetterEnd.

**Comment by kwpugh** [comment]
there might be a bigger issue here:  https://github.com/AztechMC/Modern-Industrialization/pull/223

for my reference.

**Comment by kwpugh** [comment]
Sounds like the biome api doesn't support this at the moment and there are hacky ways to get it to work.  I will look into that, but might likely wait until there is an official fabric solution.

**Comment by MJRamon** [comment]
Yet Randore uses foundInTheEnd() and ores are spawning.

**Comment by kwpugh** [comment]
In the BetterEnd Biomes?

**Comment by MJRamon** [comment]
> 

Yes, as stated in first post.

**Comment by kwpugh** [comment]
Hmm, just started a fresh world to test, went to a BetterEnd biome and this:

![2022-01-13_06 55 01](https://user-images.githubusercontent.com/8809210/149334189-717aeb14-d673-4e17-bcfe-e925752198a2.png)

**Comment by kwpugh** [comment]
This is better (pun intended)  

![2022-01-13_08 24 29](https://user-images.githubusercontent.com/8809210/149348080-939c5dce-84bb-439c-8b6a-82a96139ad42.png)

**Comment by MJRamon** [comment]
Either I had a very bad luck, or something broke on my end. Need more research looks like.

**Comment by kwpugh** [comment]
No, this is with some  changes I made to my code.  end Gobber is not showing up in the BetterEnd biomes in the current release.  Showing showing pics that I was able to get it working.

**Comment by kwpugh** [comment]
Also, seems like with BetterEnd you might need to up the chunk chances in the config from the default value.  This screen shot is with the value doubled.  BetterEnd is crowding the feature gen which seems to make  gobber end ore less likely than normal, at least I think that is what is happening.

![2022-01-13_12 07 12](https://user-images.githubusercontent.com/8809210/149385196-55fb1b6b-db09-42d4-88ca-882e2fc25d91.png)

**Comment by kwpugh** [comment]
I will finish up the updates today and push an update with the end gen fixes

**Comment by MJRamon** [comment]
> I will finish up the updates today and push an update with the end gen fixes I want to do some more flying around and digging to confirm things. I have noticed that my Oregen and rand'ore are very inconsistent, some biomes seems to get none in various places while lots in others, very strange. Statistically, each sample should be fairly close to each other in amount. where it happens, it affects both mine and rand'ore though.

Ah, I see. Well, at least you've got it working.
As for inconsistence - looks like some things are fighting with each other, and I do believe it's on Minecraft's end, cause BetterEnd generation uses Mojang feature system (similar to datapack process).

**Comment by kwpugh** [comment]
I don't believe that is true, it looks like biome creation is in code: 
https://github.com/paulevsGitch/BetterEnd/blob/1.18/src/main/java/ru/betterend/registry/EndBiomes.java

https://github.com/paulevsGitch/BetterEnd/blob/989bd387d15905d4220dff1b5d62acc8a9e2c55f/src/main/java/ru/betterend/world/biome/land/GlowingGrasslandsBiome.java#L13

As examples.  I appears that they essentially created a Biome API on top of the Fabric Biome API, if I am understanding their code (which I might not be).

It does use the minecraft configured and placed feature system, if that it what you are referring to, which everyone needs to use to get ores and such injected into world gen.

It doesn't appear they are doing datapack biomes.

**Comment by kwpugh** [comment]
Also, I believe that both BetterEnd and BetterNether replaces the default generator for those dimensions, that is why we have had so many compatibility problems.

**Comment by kwpugh** [comment]
Just pushed v60 with the fixes for End biomes ore spawning.  Let me know if you have more issues.  Not perfect, but it works with most BetterEnd biomes, albeit inconsistently.

**Comment by MJRamon** [comment]
> Just pushed v60 with the fixes for End biomes ore spawning. Let me know if you have more issues. Not perfect, but it works with most BetterEnd biomes, albeit inconsistently.

Thanks, will test. Mind updating github aslo for references?
