### ISSUE TITLE
[1.18.1] Rings and medallions durability and cooldown

### ISSUE THREAD

**Issue by MJRamon** [kwpugh/gobber_fabric-1.17#52]
Right now, not all items in Gobber have durability and cooldown - some of them are instant and eternal.

Can you please add this parameters and configs for all the items?

**Comment by kwpugh** [comment]
I will  take a look at these individually.  I  generally dislike rings and such that take durability and I  use cooldowns sparingly.

**Comment by MJRamon** [comment]
Sure. But it's needed in multiplayer environment for balance reasons.

**Comment by kwpugh** [comment]
I've looked through the items and I'm happy with where they are.  I don't want to add more logic for durability which I personally don't like.  If they are too unbalanced for you, there are many choices for mods that might fit your needs.
