### ISSUE TITLE
[1.18/1.18.1] Incompatibility with Slabby

### ISSUE THREAD

**Issue by cshamy01** [kwpugh/gobber_fabric-1.17#53]
So today I had tried to put this into my personal modpack, and I don't know much about this stuff but by the looks of it, it seems to be incompatible with the mod Slabby. Down below is the crash report. I hope this helps. I also tried an older version, and ran into the same issue. Gobber looks really sweet, so I hope that is something that can be fixed. Thanks

[crash-2022-01-19_16.22.30-client.txt](https://github.com/kwpugh/gobber_fabric-1.17/files/7900729/crash-2022-01-19_16.22.30-client.txt)

**Comment by kwpugh** [comment]
Looks like it is crashing on Slabby.  You need to open with them.

**Comment by kwpugh** [comment]
Slabby  crashes without Gobber.   Please  contact that mods author.
