### ISSUE TITLE
[1.18.1] Gobber Lucky Ore spawns in the Nether

### ISSUE THREAD

**Issue by pewblaze** [kwpugh/gobber_fabric-1.17#54]
Modloader: Fabric

Gobber Lucky Ore spawns in the Nether? (Terralith Biome)
![2022-01-25_14 18 00](https://user-images.githubusercontent.com/96242065/150984566-0405330f-3464-47a4-af38-3be972eaee29.png)

**Comment by kwpugh** [comment]
which  versions of Gobber and Terralith?

**Comment by pewblaze** [comment]
Gobber2-Fabric-1.18.1-2.5.61.jar
Terralith_v2.0.12_Fabric+Forge.jar

**Comment by kwpugh** [comment]
which version of Fabric API are you using?

**Comment by pewblaze** [comment]
fabric-api-0.46.2+1.18

**Comment by kwpugh** [comment]
Cannot replicate.
