### ISSUE TITLE
[1.18.1] Ring of Swiftness does not provide Jump Boost as listed on CurseForge page

### ISSUE THREAD

**Issue by BR0674** [kwpugh/gobber_fabric-1.17#55]
Loader: Fabric
Gobber version: 2.5.58
FabricAPI version: 0.45.0

**Comment by kwpugh** [comment]
Ah, I will update that description, the ring doesn’t have jump boost.

**Comment by BR0674** [comment]
Is there a way to make it apply jump boost in the config?

**Comment by kwpugh** [comment]
There  is  no  code in the item for jump, so the config is irrelevant.

**Comment by kwpugh** [comment]
combining the speed  and jump boost didn't quite  work together effectively, so  I dropped the jump part.
