### ISSUE TITLE
[1.18.1] Suggestion: make staff of clearing use a tag instead of predefined stuff in code

### ISSUE THREAD

**Issue by WhitePhant0m** [kwpugh/gobber_fabric-1.17#57]
Would be nice to be able to define what things it can clear with tags, so pack devs/server owners could add modded flowers and such to the list of things it can clear.

The tag could be named `#gobber2:clearing_staff_clearable` or something else if you come up with something better.

It would include `#minecraft:flowers` by default, and maybe some plants.

**Comment by kwpugh** [comment]
Great idea.  I now know how to do that.

**Comment by kwpugh** [comment]
My memory is awful this early in the morning, I already did that.
<img width="816" alt="Screen Shot 2022-02-09 at 6 26 25 AM" src="https://user-images.githubusercontent.com/8809210/153200946-72687124-727b-454b-bc1b-9688116114ac.png">

I created tags in the "c" namespace for   this purpose.

**Comment by kwpugh** [comment]
[gobber2_datapack.zip](https://github.com/kwpugh/gobber_fabric-1.17/files/8032714/gobber2_datapack.zip)

**Comment by kwpugh** [comment]
Biomes You'll Go is a good example
<img width="1107" alt="Screen Shot 2022-02-09 at 6 45 17 AM" src="https://user-images.githubusercontent.com/8809210/153203812-ebf4bdaa-9800-4560-a227-3a9291ce465e.png">

**Comment by WhitePhant0m** [comment]
Ah, I see.

When I was using it in-game it didn't seem to clear flowers consistently(at least when looking at the tags the flowers/bushes had), so I thought it didn't support tag usage in it, it's just that not one item in this pack I was using it in seemed to have c:flowers/bushes/grass block tag, and they just used the vanilla tag(`#minecraft:flowers`) for their flowers.

**Comment by kwpugh** [comment]
I  will add a check for the Minecraft flowers tag as  well.
<img width="367" alt="Screen Shot 2022-02-09 at 7 26 24 AM" src="https://user-images.githubusercontent.com/8809210/153210438-0eae614a-51ae-4b41-9ff9-2e5fdeb81ec1.png">

**Comment by kwpugh** [comment]
I'm kinda throwing the  kitchen sink at the testing, lol

**Comment by kwpugh** [comment]
I believe this provide options for modpack makers and players to add more plants and such via the datapack.  The sample datapack is available in the darapack channel in my Discord server.
