### ISSUE TITLE
Airwalking won't walk

### ISSUE THREAD

**Issue by xienwolf** [kwpugh/gobber_fabric-1.17#59]
Using the mod in the Origins Adventures pack.  Looked at the json in config and don't see anything that could disable the ring of airwalking from allowing you to walk on air.

I just made the thing, and I don't walk on air, but I can click to place glass, which doesn't seem to be in the description, but is in the config.

What I have tried: Having the ring in my hotbar with the ring selected and then walking off a block.  I fall as normal.  Tried in offhand, in inventory,  Tried to put in the Trinket slot Hands.  Can get the ring to do nothing except place glass.

I tried disabling the place glass ability in case it was a "this or that" feature.  Still unable to walk on air.

**Comment by kwpugh** [comment]
using 1.18.2?
