### ISSUE TITLE
[1.17.1] Paxel Suggestion

### ISSUE THREAD

**Issue by CanINotUseTruth** [kwpugh/gobber_fabric-1.17#6]
Simple suggestion for the paxel, allow it to have all the right click functionality of the tools it's made from eg. stripping wood or making path blocks.

**Comment by kwpugh** [comment]
they make paths and strip looks already.   What do. you mean?

**Comment by CanINotUseTruth** [comment]
I did some more testing, apologies I didn't really consider I was using modded log types. Though the end tree axe does work with the log types from Charm and the paxel does not.

**Comment by kwpugh** [comment]
ok, that might be a different situation for me to look into.

**Comment by Muffintiem** [comment]
I had the same issue with Cinnamon in Croptopia. Axes work fine but Paxels do not.

**Comment by kwpugh** [comment]
With the latest?  I. fixed the problem in v36.

**Comment by kwpugh** [comment]
Oh, I see, its strips but does not drop the cinnamon, ugg.

**Comment by kwpugh** [comment]
Croptopia fixed this by adding cinnamon to the minecraft tags.
