### ISSUE TITLE
[1.18.2] Dragon Armor grants Flight via direct ability modification, causing undefined behaviour when used with other mods

### ISSUE THREAD

**Issue by gliscowo** [kwpugh/gobber_fabric-1.17#60]
As is clearly visible on [line 70 of the DragonArmor class](https://github.com/kwpugh/gobber_fabric-1.17/blob/242a175af60c47b7b4dd5c39480a2b42f4c436b0/src/main/java/com/kwpugh/gobber2/items/armor/DragonArmor.java#L70), the player's flight ability is being directly modified. This causes an exception (raised by PlayerAbilityLib[PAL]) and possibly undefined behaviour if different mods modify the ability directly. Instead, [PAL](https://github.com/Ladysnake/PlayerAbilityLib)'s `AbilitySource` system should be used, which will prevent the exception and make sure all abilities always match their expected state. Implementation is trivial, you can reference their README, and the library can easily be JiJ'd
Cheers

**Comment by kwpugh** [comment]
I'll take a look.  Risk of issue is reduced because the logic does not execute if the player is not wearing the armor.  I generally avoid 3rd party libs unless absolutely necessary.

I notice that PAL hasn't been updated since 1.18.pre1.  Gobber is currently available for 1.18.2 and 1.19 22w11a.

**Comment by kwpugh** [comment]
I really don't see a need for this for the sake of one item.

Thanks for the suggestion.
