### ISSUE TITLE
[22w13a] Bows causing crash

### ISSUE THREAD

**Issue by Muffintiem** [kwpugh/gobber_fabric-1.17#61]
In the latest snapshot bows from both More Gems and Gobber are causing a crash. Vanilla bows work ok. I have the latest versions of both along with the latest version of Greater Eye.

**Comment by kwpugh** [comment]
A crash report would be helpful for me to know what is going on.

**Comment by kwpugh** [comment]
I assume 22w13a?

**Comment by Muffintiem** [comment]
22w14a

**Comment by kwpugh** [comment]
Ahh.  Looks like they did some variable name changes.  It will be fixed when I release for 22w14a.

**Comment by Muffintiem** [comment]
Awesome. I can't wait to see how the more OP armors stand up to the Warden.

**Comment by kwpugh** [comment]
Lol, the crash with the bows is because changed the method the signature for playing a sound on the bow.

**Comment by kwpugh** [comment]
on the defaults, you can take a beating from the Warden, from testing in 22w13a.

you can always tweak the armor stats in the config.

Sword of the Sniper takes a few hits to kill the Warden.

**Comment by kwpugh** [comment]
fixed in 22w14a  release.
