### ISSUE TITLE
[1.18.2] Mixin error

### ISSUE THREAD

**Issue by Sunconure11** [kwpugh/gobber_fabric-1.17#62]
https://pastebin.com/4SigZzdJ

**Comment by kwpugh** [comment]
Is the game crashing or causing an issue?

**Comment by Sunconure11** [comment]
Crashing

**Comment by kwpugh** [comment]
Try this.


[Gobber2-Fabric-1.18.2-2.5.71.jar.zip](https://github.com/kwpugh/gobber_fabric-1.17/files/8459314/Gobber2-Fabric-1.18.2-2.5.71.jar.zip)

**Comment by Sunconure11** [comment]
It's probably fixed, but I am working with getting everything in a big-ass modpack updated and cleaning out as many compat issues as possible, so, I will re-open this if this comes back later on, or if I turn out to be wrong.

**Comment by kwpugh** [comment]
Ok.  I will push the update to CF, since I'm pretty confident.  I disabled the mixin in question.  I will be on the road for the next 10 day, so won't be able to do much later if I'm wrong,  Fingers crossed.

**Comment by kwpugh** [comment]
removed  this mixin in the next update.
