### ISSUE TITLE
[1.18.2] Crashing when switching pages in creative mode

### ISSUE THREAD

**Issue by Farianir** [kwpugh/gobber_fabric-1.17#64]
Gobber cousing crash when i switch pages in creative mode but items works properly.
Log shows that AlloyForgery is the problem. 

https://pastebin.com/QXPkmGNX

**Comment by kwpugh** [comment]
what makes you believe Gobber is the cause?

**Comment by Farianir** [comment]
Because without this "mod" you can browse pages properly in creative mode and as the log shows it is related to AlloyForgery.
The mod itself works fine, but these pages don't work as they should.

I am closing the thread because the problem is due to the large number of mods in the package and not from the Gobber malfunction + I leave it as a clue if someone encounters this problem again.
