### ISSUE TITLE
[Feature Request]  Add the possibility to disable gliding with Dragon Armor

### ISSUE THREAD

**Issue by MoeHunt3r** [kwpugh/gobber_fabric-1.17#69]
Yes, gliding is nice.
But sometimes it's kinda annoying and it would be great to have a way to disable the gliding.

**Comment by kwpugh** [comment]
Dragon armor doesn't have gliding, that is  only the End armor.

**Comment by kwpugh** [comment]
and the gliding  can be disabled.

<img width="282" alt="Screen Shot 2022-05-16 at 7 55 22 AM" src="https://user-images.githubusercontent.com/8809210/168597295-43e84e79-8835-4932-b56f-4d82217a1522.png">

**Comment by kwpugh** [comment]
I don't see anything actionable.
