### ISSUE TITLE
[1.17.1] Silk Touch hammer reverts to non silk touch after pressing shift

### ISSUE THREAD

**Issue by rc8marcelo** [kwpugh/gobber_fabric-1.17#7]
So I'm not sure if this is a bug or if there's a toggle to make it work with silk touch again but I noticed after I updated to the latest version (.34), after I pressed shift to get a single block, the following block breaks I do without shift becomes non-silk touch and pressing shift again doesn't  do anything to revert it back.

Oddly though, I went back to the overworld after seeing this happen and tested breaking some stone and iron ore and it broke in silk touch. I'm attaching a vid of what happened in the end (where I encountered the possible bug)

https://user-images.githubusercontent.com/341493/127768190-9f3745aa-09bc-4d93-b5e2-b5cece72ceff.mp4

**Comment by kwpugh** [comment]
This is odd.  I tried and I cannot replicate it.I get silk touch drops all the time.  Can you post a recent system log and a. list of your mods?

**Comment by rc8marcelo** [comment]
How do I post my system log?

here are all my mods and data packs being used:

![image](https://user-images.githubusercontent.com/341493/127773740-efae80de-cc23-4eab-8ac6-1da01fd41d14.png)

![image](https://user-images.githubusercontent.com/341493/127773750-5ac757b7-71a7-4413-9155-9d5165ba8475.png)

**Comment by kwpugh** [comment]
put. it on gist an post a link

https://gist.github.com

**Comment by kwpugh** [comment]
This is. what I get:   https://www.icloud.com/iclouddrive/0x81S9kdAfWXw-Dw_B4RurKOg#Screen_Recording_2021-08-01_at_9.03.40_AM

**Comment by rc8marcelo** [comment]
Just to clarify, by system log do you mean the logs from windows event viewer?

Update:

I restarted Minecraft and it appears that it's back to Silk Touch and I can no longer replicate the bug. I have no idea why though. I was thinking this might have been part of my previous issue with excavators but I'm not so sure anymore.

**Comment by kwpugh** [comment]
Any logs with error may be too difficult to find at this point if you cannot replicate.   If it does happen again, grab the latest.log from the /logs folder within your Minecraft instance.

**Comment by rc8marcelo** [comment]
I think I found the logs from when I had the error, thanks for clarifying where the logs were haha

https://gist.github.com/rc8marcelo/469f523dbd01c4417384d241c4fc3670

**Comment by kwpugh** [comment]
ok.  Looking through the log doesn't show anything unusual.  If it shows up again, let me know.

**Comment by kwpugh** [comment]
No further reports and I am unable to replicate.  IF some else reports the same issue, I will re-open.
