### ISSUE TITLE
[1.19] Ring of Miner still delay break even after config changed to false

### ISSUE THREAD

**Issue by crest1993** [kwpugh/gobber_fabric-1.17#74]
Minecraft 1.19
Fabric Loader 14.7
fabric-api-0.55.3+1.19
Gobber2-Fabric-1.19.0-2.6.16

**Comment by kwpugh** [comment]
The ring no longer has an instant-break option.  The ringMinerDelayedBreak config setting is to slow down the breaking a bit for slower computers.  When set to false, the breaking will occur in one cycle.  While set to true, there is a pause between each block break.
