### ISSUE TITLE
Paxels not acting as pickaxes

### ISSUE THREAD

**Issue by Muffintiem** [kwpugh/gobber_fabric-1.17#75]
When a paxel is used on block that is supposed to be mineable (stone or ores) it drops nothing. It works fine on dirt, gravel, sand, and wood.

**Comment by kwpugh** [comment]
Which mod version?

**Comment by Muffintiem** [comment]
1.19.0-2.6.16

**Comment by kwpugh** [comment]
Which panels?  I just tried with the Gobber Paxel and the End Paxel and both worked fine on stone and ores.

**Comment by Muffintiem** [comment]
It was both the End and Stars ones for me. It's a personal mod pack test instance with several other mods so I'm wondering if it is some sort of conflict.

Mods:
  [✔️] advancementinfo-1.19-fabric0.53.3-1.3.1
  [✔️] animal_feeding_trough-1.0.3+1.19
  [✔️] architectury-5.7.27-fabric
  [✔️] badpackets-fabric-0.1.2
  [✔️] bclib-2.0.4
  [✔️] better-end-2.0.1
  [✔️] better-nether-7.0.1
  [✔️] betterspawnercontrol-fabric_1.19.x-1.7
  [✔️] biomemakeover-FABRIC-1.19-beta-1.5.2
  [✔️] BOMD-1.4.1-1.19
  [✔️] caracal-1.19-1.3.8
  [✔️] cardinal-components-api-5.0.0-beta.1
  [✔️] cats-expanded-1.2.0+1.19.0
  [✔️] cave-enhancements-1.2.5
  [✔️] cem-0.7.1
  [✔️] cloth-config-7.0.65-fabric
  [✔️] collective-fabric-1.19.x-4.27
  [✔️] ColourfulGoats-1.19-Fabric-v1.1
  [✔️] configurableextramobdrops-fabric_1.19.x-2.0
  [✔️] CreaturesFromTheSnow-2.2.0+1.19
  [✔️] crockpot-0.9.1+1.19
  [✔️] Croptopia-1.19-FABRIC-2.0.5
  [✔️] dismountentity-fabric_1.19.x-1.7
  [✔️] duckling-2.0.0-fabric
  [✔️] ecologics-fabric-1.19-2.0.1
  [✔️] effective-1.2.2
  [✔️] enderscape-0.3.0
  [✔️] Enhanced_Celestials-fabric-1.19-2.0.0.0
  [✔️] fabric-api-0.55.3+1.19
  [✔️] fabric-language-kotlin-1.8.0+kotlin.1.7.0
  [✔️] fabric-start-the-music-0.4.4
  [✔️] fish_of_thieves-mc1.19-v2.0.2-fabric
  [✔️] forgotten_features-1.1+1.19
  [✔️] friendsandfoes-fabric-mc1.19-1.5.1
  [✔️] geckolib-fabric-1.19-3.1.2
  [✔️] Gobber2-Fabric-1.19.0-2.6.16
  [✔️] GreaterEye-Fabric-1.19.0-1.4.12
  [✔️] grind-enchantments-1.6.4+1.19
  [✔️] grindstonesharpertools-fabric_1.19.x-1.8
  [✔️] grizzlybear-1.19-1.3
  [✔️] illuminations-1.10.5
  [✔️] indypets-0.8.1-1.19
  [✔️] inventorytotem-fabric_1.19.x-1.7
  [✔️] LimitMobSpawn-19.0-fabric
  [✔️] lootgoblins-1.0.8
  [✔️] mangrove-swamp-huts-1.0.0
  [✔️] mobscarecrow-2.2.0
  [✔️] modmenu-4.0.0
  [✔️] mooshroomtweaks-fabric_1.19.x-1.8
  [✔️] more-axolotls-1.0.2-1.19
  [✔️] MoreGems-Fabric-1.19.0-1.4.19
  [✔️] more-geodes-1.4.3
  [✔️] naturalist-fabric-2.0.0-1.19
  [✔️] netherportalspread-fabric_1.19.x-5.9
  [✔️] nohostilesaroundcampfire-fabric_1.19.x-4.0
  [✔️] numismatic-overhaul-0.2.2+1.19
  [✔️] onsoulfire-1.19-1
  [✔️] owo-lib-0.7.3+1.19
  [✔️] petnames-fabric_1.19.x-1.8
  [✔️] pickyourpoison-1.0.9
  [✔️] probablychests-0.4.4
  [✔️] randombonemealflowers-fabric_1.19.x-1.8
  [✔️] randomsheepcolours-fabric_1.19.x-1.8
  [✔️] repurposed_structures_fabric-6.0.2+1.19
  [✔️] respawningshulkers-fabric_1.19.x-1.8
  [✔️] RoughlyEnoughItems-9.0.484
  [✔️] SimplyHouses-1.1.1-1.19-fabric
  [✔️] skylorlib-1.4.0
  [✔️] snowballsfreezemobs-fabric_1.19.x-1.7
  [✔️] sonic_deflect-1.0.0+1.19
  [✔️] spelunker-1.5.0
  [✔️] spidersproducewebs-fabric_1.19.x-1.7
  [✔️] statuseffecttimer-1.1.1+1.19
  [✔️] stoneholm-1.4.4
  [✔️] Subterrestrial-1.0.3
  [✔️] TheExtractinator-1.10
  [✔️] villagerdeathmessages-fabric_1.19.x-2.3
  [✔️] villagernames-fabric_1.19.x-3.6
  [✔️] visuality-0.5.0
  [✔️] windchimes-1.2.1
  [✔️] wraith-harvestscythes-2.5.2
  [✔️] wthit-fabric-5.3.0
  [✔️] Xaeros_Minimap_22.9.2_Fabric_1.19
  [✔️] XaerosWorldMap_1.23.2_Fabric_1.19
  [✔️] your-reputation-0.1.3+1.19
  [✔️] zombiehorsespawn-fabric_1.19.x-3.1

**Comment by kwpugh** [comment]
Try without BCLib, Better Nether and Better End

**Comment by Muffintiem** [comment]
It wasn't BCLib this time. I was able to narrow it down and the conflict is with Forgotten Features, which adds things that were supposed to be added in 1.19 like fireflies and birch forest enhancements.

**Comment by Muffintiem** [comment]
I downloaded the latest update of Forgotten Features and it seems the issue has fixed itself. Yay.
