### ISSUE TITLE
[1.19]when i use end hammer to break fire, dragon head or some entities  ,client will crash

### ISSUE THREAD

**Issue by NullExistence1994** [kwpugh/gobber_fabric-1.17#76]
[crash-2022-06-16_15.22.44-client.txt](https://github.com/kwpugh/gobber_fabric-1.17/files/8916596/crash-2022-06-16_15.22.44-client.txt)
[crash-2022-06-16_15.11.20-client.txt](https://github.com/kwpugh/gobber_fabric-1.17/files/8916598/crash-2022-06-16_15.11.20-client.txt)

**Comment by kwpugh** [comment]
Are you running single player or on a server?

**Comment by kwpugh** [comment]
I just tested and the hammer worked fine on fire.

**Comment by NullExistence1994** [comment]
> 

on server and no log

**Comment by kwpugh** [comment]
Did the server crash or just the client?  why no server log?

**Comment by NullExistence1994** [comment]
> Did the server crash or just the client? why no server log?

The server is running normally 
just client crash

**Comment by kwpugh** [comment]
I tested on single player and on my test server, no issues on either.  I suspect you have a mod that is conflicting somehow.  Do you have any mods that alter/change tool behavior or mining?

**Comment by NullExistence1994** [comment]
> I tested on single player and on my test server, no issues on either. I suspect you have a mod that is conflicting somehow. Do you have any mods that alter/change tool behavior or mining?
treeharvester
I'll test it

**Comment by NullExistence1994** [comment]
> I tested on single player and on my test server, no issues on either. I suspect you have a mod that is conflicting somehow. Do you have any mods that alter/change tool behavior or mining?

Previously used 2.0.1
I updated it to 2.0.2 still have this problem

**Comment by NullExistence1994** [comment]
oh there is new crash report
Maybe it can help
[crash-2022-06-17_00.46.52-client.txt](https://github.com/kwpugh/gobber_fabric-1.17/files/8920915/crash-2022-06-17_00.46.52-client.txt)

**Comment by NullExistence1994** [comment]
I also submitted an issue on the better nether side
It looks like the problem of enchantment

**Comment by NullExistence1994** [comment]
BetterNether now compatible with gobber2
