### ISSUE TITLE
[1.18.2] Minecraft does't lauch

### ISSUE THREAD

**Issue by EchoSimps** [kwpugh/gobber_fabric-1.17#77]
I added Gobber 1.18.2 in the mod folder and all the dependencies but when i try launching the game it says:

> Mod 'Gobber2' (gobber2) 2.5.74 requires any version of cloth-config2, which is missing!

idk what i did wrong but i have cloth-confing in my mod folder and i checked if it was 1.18.2 and it is... idk

what the launcher says:
![Screenshot 2022-06-19 155857](https://user-images.githubusercontent.com/107801457/174484790-89bfd2c3-70fe-4347-b2e3-4ba5ff7028e1.png)

all my installed mods:
![Screenshot 2022-06-19 160007](https://user-images.githubusercontent.com/107801457/174484829-85527fc6-3f32-4435-8639-0f5ac523b9a3.png)

**Comment by kwpugh** [comment]
you have cloth config for forge, not fabric
