### ISSUE TITLE
[1.19] client "Internal server error" with farmer ring in Edenring dimension

### ISSUE THREAD

**Issue by NullExistence1994** [kwpugh/gobber_fabric-1.17#78]
[latest.log](https://github.com/kwpugh/gobber_fabric-1.17/files/8939831/latest.log)

**Comment by kwpugh** [comment]
Refer to https://github.com/paulevsGitch/EdenRing/issues/35.

**Comment by kwpugh** [comment]
this is being fixed by the EdenRing author.
