### ISSUE TITLE
[1.16.5] Hammer randomly loses silk touch encantment ability over time.

### ISSUE THREAD

**Issue by gluest1c** [kwpugh/gobber_fabric-1.17#8]

**Comment by kwpugh** [comment]
I cannot replicate this on. my side.   Can you provide a system log so I can see what you are running?

**Comment by kwpugh** [comment]
I tried about 30 sets of ores and other blocks with the hammers and silk drops every time.   It is very odd that a silk touch might stop working randomly unless there is other code running from another mod that interferes with it.  

Did you notice any pattern at all?  Is there a particular block or blocks that do not drop on silk touch?

**Comment by gluest1c** [comment]
I tried to do a few things using other tools from this mod, but I couldn't figure out what exactly is causing this problem, because it happens absolutely randomly.
Re-entering the game fixes this error.
video proof: https://drive.google.com/file/d/1wuQ6R9MnYGZG4PY-zbbTtWbk2W0LbHfO/view?usp=sharing

**Comment by gluest1c** [comment]
> I cannot replicate this on. my side. Can you provide a system log so I can see what you are running?
Of course, if you tell me how I can do it.

**Comment by kwpugh** [comment]
Do a fresh start up from the launcher, go into the world, exit, grab the latest.log from the /logs folder in your Minecraft folder.

I do not doubt it is happening to you, I just can't replicate, which makes it difficult to isolate what the problem is and fix it.

**Comment by gluest1c** [comment]
[latest.log](https://github.com/kwpugh/gobber_fabric-1.17/files/6988063/latest.log)
Is that it?

**Comment by kwpugh** [comment]
that log shows 1.16.5.  Are you running 1.16.5 or 1.17.1?

**Comment by gluest1c** [comment]
1.16.5

**Comment by kwpugh** [comment]
ah, the 1.16.5 version doesn't have support for silk touch, so that would. explain it.  I was testing with 1.17.1

**Comment by gluest1c** [comment]
Oh... I just noticed that I wrote about it under the wrong discussion... I'm really sorry for that and for disturbing you.

**Comment by kwpugh** [comment]
no prob.  I creating a test build right now that should fix it

**Comment by kwpugh** [comment]
fingers crossed

**Comment by kwpugh** [comment]
[Gobber2-Fabric_1.16.5-2.3.75.jar.zip](https://github.com/kwpugh/gobber_fabric-1.17/files/6988115/Gobber2-Fabric_1.16.5-2.3.75.jar.zip)

Give this a try

**Comment by kwpugh** [comment]
In 1.16.5, I'm surprised silk touch worked at all, let alone randomly.  there was no code to support it.

**Comment by gluest1c** [comment]
> [Gobber2-Fabric_1.16.5-2.3.75.jar.zip](https://github.com/kwpugh/gobber_fabric-1.17/files/6988115/Gobber2-Fabric_1.16.5-2.3.75.jar.zip)
> 
> Give this a try

It still happens...

**Comment by gluest1c** [comment]
> In 1.16.5, I'm surprised silk touch worked at all, let alone randomly. there was no code to support it.

Then let's just forget about it lol.

**Comment by kwpugh** [comment]
did you grab a new hammer and enchant it, might. not work with an existing one.

**Comment by gluest1c** [comment]
> did you grab a new hammer and enchant it, might. not work with an existing one.

I did, even deleted previous one.

**Comment by kwpugh** [comment]
[Gobber2-Fabric_1.16.5-2.3.75.jar.zip](https://github.com/kwpugh/gobber_fabric-1.17/files/6988300/Gobber2-Fabric_1.16.5-2.3.75.jar.zip)

Another try.

**Comment by gluest1c** [comment]
Now it works perfect :0

**Comment by kwpugh** [comment]
cool, thanks,  if. you see anything else, let me know.

**Comment by gluest1c** [comment]
Sure! Good luck
