### ISSUE TITLE
[1.17.1] Add categories to meat food items

### ISSUE THREAD

**Issue by NotAPotter** [kwpugh/gobber_fabric-1.17#9]
This I guess is a compatibility problem with origins, but it seems as a piglin I can't eat the meat-related items.

**Comment by NotAPotter** [comment]
I'm still a player with origins, just with certain diet restrictions.

**Comment by kwpugh** [comment]
The food in Gobber is added as standard vanilla food, I don't know how Origins sets diet restrictions

**Comment by kwpugh** [comment]
which add-on adds piglins?

**Comment by kwpugh** [comment]
[Gobber2-Fabric-1.17.1-2.4.38.jar.zip](https://github.com/kwpugh/gobber_fabric-1.17/files/6987302/Gobber2-Fabric-1.17.1-2.4.38.jar.zip)

Try this version.   Specifically the gooey beefs and beefstews

**Comment by NotAPotter** [comment]
> which add-on adds piglins?

Extra origins. Sorry for not specifying.

**Comment by NotAPotter** [comment]
This new version seems to have sorted the problem out, thank you.

**Comment by kwpugh** [comment]
ok, I will push an update shortly
